name: microbiome-analysis-binder
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base
  - r-ggplot2
  - r-vegan
  - r-ape
  - r-ggrepel
  - r-picante
  - bioconductor-phyloseq
  - maaslin2>=1
